POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Adam",
  "firstName": "Adam",
  "lastName": "Lee",
  "gender": "Male",
  "birthDate": "1985-6-11",
  "email": "adamlee@test.com",
  "password": "adamlee",
  "profilePic": "https://source.unsplash.com/weekly?man"
}

POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "janelee@test.com",
  "password": "janelee"
}

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMzMjQ2OTF9.ZQWnaRWMKoM3Nv6yUU2IpRkXEqSWs1lSIjYF7D51XcA

GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMzMjQ2OTF9.ZQWnaRWMKoM3Nv6yUU2IpRkXEqSWs1lSIjYF7D51XcA

GET http://localhost:3000/my-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMzMjc3MjV9.5CeARPX_n4OKPBp1v9tah8haKzbn0cObKoA_pzmorko

POST http://localhost:3000/my-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMzMjc3MjV9.5CeARPX_n4OKPBp1v9tah8haKzbn0cObKoA_pzmorko
Content-Type: application/json

{
  "username": "Adam",
  "firstName": "Adam",
  "lastName": "Evans",
  "gender": "Male",
  "birthDate": "1985-6-11",
  "email": "adamevans@test.com",
  "password": "adamevans",
  "profilePic": "https://source.unsplash.com/weekly?man"
}

POST http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMzMjQ2OTF9.ZQWnaRWMKoM3Nv6yUU2IpRkXEqSWs1lSIjYF7D51XcA

DELETE http://localhost:3000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMzMjQ2OTF9.ZQWnaRWMKoM3Nv6yUU2IpRkXEqSWs1lSIjYF7D51XcA