POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "JoeLim",
  "firstName": "Joe",
  "lastName": "Lim",
  "gender": "Male",
  "birthDate": "1984-5-11",
  "email": "joelim@test.com",
  "password": "joelim",
  "profilePic": "https://source.unsplash.com/weekly?man"
}

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "joelim@test.com",
  "password": "joelim"
}

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMyNzE4MjB9.5Gzs1p11tyOaYn8aMkxDRSEowT1ITbUUIufHHOW4rZg

GET http://localhost:3000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMyNzIzMjR9.Z_INDJmnwJi0lPbwTMRhYBlIqTKWSZ98P07nGoL6TEw

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMyNzQ3ODl9.9RRi_24gfxsejlyP9dkm7HGyQ225x2xLAf08Sd26dPY

POST http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMyNzQ0Nzd9.7imEI7D4PKhJkU8FrYBlbPDJTPj_LhhJJ5b-Q1OTn7I
Content-Type: application/json

{
  "username": "JaneDoe",
  "firstName": "Jane",
  "lastName": "Lim",
  "gender": "Female",
  "birthDate": "1988-1-1",
  "email": "jane.doe@test.com",
  "password": "jenny",
  "profilePic": "https://source.unsplash.com/weekly?woman"
}

POST http://localhost:3000/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMyNzE4MjB9.5Gzs1p11tyOaYn8aMkxDRSEowT1ITbUUIufHHOW4rZg

DELETE http://localhost:3000/users/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTMyNzE4MjB9.5Gzs1p11tyOaYn8aMkxDRSEowT1ITbUUIufHHOW4rZg